source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails', '4.1.2.rc1'
gem 'rails-i18n'
gem 'devise'
gem 'foreigner'
gem 'pg'
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'

gem 'spring', group: :development
gem 'capybara', group: :test

gem 'rails_12factor', group: :production
